name: CI AI Diff Parser

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Build and push Docker image
        id: build-image
        env:
          DOCKER_HOST: ${{ vars.DOCKER_HOST }}
          REGISTRY_HOST: ${{ vars.REGISTRY_HOST }}
        run: |
          pwd
          ls -l app
          chmod +x app
          ls -l app

          sudo docker -H ${DOCKER_HOST} build -t ${REGISTRY_HOST}/ai/diff-parser:v2.0 .
          sudo docker -H ${DOCKER_HOST} push ${REGISTRY_HOST}/ai/diff-parser:v2.0
